import { getColor,shade, lightness ,lighten , darken } from "@theme-ui/color";

const theme = {
  // config: {
  //   initialColorModeName: 'dark',
  //   useColorSchemeMediaQuery:'system'
  // },
  sizes: {
    container: 1200,
    videoL: 1024,
    videoM: 720,
    videoS: 640,
  },
  // colors: {
  //   text: "#56606D",
  //   body: "#56606D",
  //   heading: "#AD0009",
  //   background: "#FFF8E0",
  //   primary: "#333941",
  //   secondary: "#AD0009",
  //   third: "#05a696", 
  //   muted: "#BF0D0D",
  //   darkest: "#020426",
  //   lightest: "#ffffff"
  // },
  colors: {
    primary: "#F29E1F",
    secondary: "#05a6fe", 
    third: "#dc3856",
    background: "#1a1a1a",
    btn:"#1f1f1f",
    clickable: "#05a6fe",
    selected:"#dc3856",
    active: "#F29E1F",
    text: lightness("primary",0.9),
    body: lightness("primary",0.9),
    heading: "#F29E1F",
    muted: lightness("primary",0.9),
    darkest: "#020426",
    lightest: "#ddd",
    primary100: lighten("primary",0.3),
    primary300: lighten("primary",0.1),
    primary500: "#F29E1F",
    primary700: darken("primary",0.2),
    primary900: darken("primary",0.35),
    secondary100: lighten("secondary",0.3),
    secondary300: lighten("secondary",0.1),
    secondary500: "#05a6fe",
    secondary700: darken("secondary",0.2),
    secondary900: darken("secondary",0.35),
    third100: lighten("third",0.3),
    third300: lighten("third",0.1),
    third500: "#dc3856",
    third700: darken("third",0.2),
    third900: darken("third",0.35),
    // modes: {
    //   light: {
    //     primary: "#F29E1F",
    //     secondary: "#05a6fe", 
    //     third: "#dc3856",
    //     background: "#fadfb7",
    //     btn:"#fceacf",
    //     clickable: "#dc3856",
    //     selected: darken("primary",0.1),
    //     active: "#05a6fe",
    //     text: darken("primary",0.9),
    //     body: darken("primary",0.9),
    //     heading: darken("third",0.1),
    //     muted: darken("primary",0.9),
    //     darkest: "#020426",
    //     lightest: "#ddd",
    //     primary100: lighten("primary",0.3),
    //     primary300: lighten("primary",0.1),
    //     primary500: "#F29E1F",
    //     primary700: darken("primary",0.2),
    //     primary900: darken("primary",0.35),
    //     secondary100: lighten("secondary",0.3),
    //     secondary300: lighten("secondary",0.1),
    //     secondary500: "#05a6fe",
    //     secondary700: darken("secondary",0.2),
    //     secondary900: darken("secondary",0.35),
    //     third100: lighten("third",0.3),
    //     third300: lighten("third",0.1),
    //     third500: "#dc3856",
    //     third700: darken("third",0.2),
    //     third900: darken("third",0.35),
    //   }
    // }
  },
  fonts: {
    body: '"Helvetica Neue", sans-serif',
    heading: '"Source Code Pro","Helvetica Neue", sans-serif',
    btn: '"Source Code Pro","Helvetica Neue",sans-serif',
    nav: '"Source Code Pro","Helvetica Neue",sans-serif',
    monospace: "monospace",
    barcode:'"Libre Barcode 39 Text", sans-serif',
  },
  space: [0, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048],
  radii: {
    none:"0",
    small: "0.25rem",
    default: "0.5rem",
    pill: 9999,
  },
  borderWidths: ["0rem","0.125rem","0.25rem","0.375rem","0.5rem","0.625rem","0.75rem","1rem"],
  fontSizes: [14, 16, 18, 20, 24,28,32, 48, 64, 96],
  fontWeights: {
    body: 400,
    heading: 300,
    a: 600,
    bold: 600,
    nav: 400,
    btn: 400,
  },
  lineHeights: {
    body: 1.5,
    heading: 1,
  },
  text: {
    color: "body",
    fontFamily: "body",
    fontWeight: "body",
    lineHeight: "body",
    heading: {
      color: "heading",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontStyle: "normal",
      textTransform:"uppercase",
      fontSize: [6, 7, 8],
      p: 0,
      pb: "0.66rem",
    },
    title: {
      variant: "text.heading",
      fontSize: [7, 8],
    },
    subheading: {
      variant: "text.body",
      color: "muted",
      fontSize: [4, 5, 6],
      pb:"0.25rem"
    },
    brackets:{
      variant: "text.subheading",
      "&:before": {
        content: '"< "',
      },
      "&:after": {
        content: '" />"',
      },
    },
    barcodes: {
      variant: "text.heading",
      fontFamily: "barcode",
      textTransform:"uppercase",
      mb:0,
    },
  },
  buttons: {
    nav: {
      color: "muted",
      backgroundColor: "background",
      display: "inline-block",
      position: "relative",
      px:2,
      py:2,
      fontFamily: "nav",
      fontWeight: "nav",
      textTransform: "uppercase",
      textDecoration: "none",
      letterSpacing: [1],
      borderRadius:"none",
      border: "solid 0px currentColor",
      borderWidth: 1, 
      borderColor: "transparent",
      transition: "0.25s ease-in",
      "&.active": {
        color: "active",
        borderColor:"currentColor",
        borderRadius: "default",
      },
      "&:hover,&:focus": {
        color: "selected",
        background:"btn",
        borderColor:"currentColor",
        borderRadius: "default",
        borderTopRightRadius: "0",
        borderBottomLeftRadius: "0",
        outline:"none", 
      },
    },
    outlineBtn: {
      color: "clickable",
      backgroundColor: "btn",
      px: 3,
      py: 2,
      fontSize: [1, 2],
      fontFamily: "btn",
      fontWeight: "btn",
      letterSpacing: [1],
      textDecoration: "none",
      textTransform: "uppercase",
      border: "solid currentColor",
      borderWidth: [1],
      borderRadius: 0,
      transition: "0.2s ease-in",
      "&.active": {
        color: "active",
        background:"btn",
        borderRadius: "default",
      },
      "&:hover,&:focus": {
        color: "selected",
        background:"btn",
        borderRadius: "default",
        borderTopRightRadius: "0",
        borderBottomLeftRadius: "0",
        outline:"none", 
      },
    },
    fillBtn: {
      variant: "buttons.outlineBtn",
      color: "btn",
      backgroundColor: "clickable",
      borderColor: "clickable",
      "&.active": {
        color: "btn",
        background:"active",
        borderColor: "active",
        borderRadius: "default",
      },
      "&:hover,&:focus": {
        color: "btn",
        backgroundColor: "selected",
        borderColor: "selected",
        borderRadius: "default",
        borderTopRightRadius: "0",
        borderBottomLeftRadius: "0",
        outline:"none", 
      },
    },
    socialBtn: {
      variant: "buttons.outlineBtn",
      px: 2,
      py: 2,
      lineHeight: 1,
      mr: 2,
    },
  },
  forms: {
    label: {
      fontSize: 2,
      fontWeight: "bold",
      pb: 1,
      color:"muted",
    },
    labelRequired: {
      variant: "forms.label",
      "&:after": {
        content: '"*"',
        color: "secondary",
      },
    },
    input: {
      borderColor: "primary",
      borderStyle: "dashed",
      borderWidth: 1,
      borderRadius: 0,
      marginBottom: 3,
      fontFamily: "body",
      "&:hover,&:focus": {
        borderColor: "secondary",
        outline: "none",
      },
    },
    select: {
      borderColor: "secondary",
      borderStyle: "dashed",
      borderWidth: 1,
      borderRadius: 0,
      "&:hover,&:focus":{
        borderColor: "primary",
        outline: "none",
      },
    },
    textarea: {
      variant: "forms.input",
      resize:"none",
    },
  },
  styles: {
    root: {
      color: "body",
      fontFamily: "body",
      lineHeight: "body",
      fontWeight: "body",
    },
    h1: {
      color: "heading",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      textTransform:"uppercase",
      fontSize: [6, 7],
    },
    h2: {
      color: "heading",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: [5, 6],
    },
    h3: {
      color: "heading",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: [4, 5],
    },

    h4: {
      color: "heading",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: [3, 4],
    },
    h5: {
      color: "heading",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: [2, 3],
    },
    h6: {
      color: "heading",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: [1, 2],
    },
    p: {
      color: "body",
      fontFamily: "body",
      fontWeight: "body",
      lineHeight: "body",
      maxWidth: ["40ch","50ch","70ch"],
    },
    a: {
      color: "primary",
      textDecoration: "none",
      fontWeight: "a",
      ":hover,:focus": {
        textDecoration: "underline",
        color: "selected",
        outline:"none"  
      },
    },
    pre: {
      fontFamily: "monospace",
      overflowX: "auto",
      code: {
        color: "inherit",
      },
    },
    code: {
      fontFamily: "monospace",
      fontSize: "inherit",
    },
    table: {
      width: "100%",
      borderCollapse: "separate",
      borderSpacing: 0,
    },
    th: {
      textAlign: "left",
      borderBottomStyle: "solid",
    },
    td: {
      textAlign: "left",
      borderBottomStyle: "solid",
    },
    img: {
      maxWidth: "100%",
    },
    ol: {
      fontFamily: "body",
      fontWeight: "body",
      lineHeight: "body",
    },
    ul: {
      fontFamily: "body",
      fontWeight: "body",
      lineHeight: "body",
    },
    li: {
      fontFamily: "body",
      fontWeight: "body",
      lineHeight: "body",
    },
  },
};

export default theme;
